image: node:lts

pages:
  cache:
    paths:
    - node_modules/

  stage: deploy
  script:
  - npm install -g @angular/cli@6.2.1
  - npm install
  - ng build
  - mkdir -p public
  - mv dist/tp-note/* public/
  artifacts:
    paths:
    - public
  only:
  - master
  - pages